### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [zenkbaries/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by zenkbaries** [comment]
Ive been researching a bit for a while and still not sure. Thought the mobile tag is already added (it's a default in Bootstrap where it is a :mobile first:.
And you give point out the specific?

**Comment by kenmazaika** [comment]
There's 1 line of code you need to add to your HTML.  It starts with

```
<meta
```

Check out the bootstrap documentation:
http://getbootstrap.com/css/

Scroll down to the "Mobile First" header.  There you will find a sentence that looks like this:

> To ensure proper rendering and touch zooming, add the viewport meta tag to your `<head>`.

Hope this helps!

**Comment by zenkbaries** [comment]
yes  i found it... i did read that section but didnt think that this is the answer  ii guess i looked too hard 

now other issue came up with footer not properly aligned when in desktop mode

**Comment by zenkbaries** [comment]
Ive added '<meta name="viewport" content="width=device-width, initial-scale=1">' in the <head> section.

also i removed the 'col-sm-6' from      '<div class="col-xs-12 footer-blurb">' in line  76 of  application.html.erb.  I'm having issue with that in desktop mode. it get displayed in middle, not riight-aligned. removing 'col-sm-6' seems to solve it

**Comment by kenmazaika** [comment]
Awesome!  Thumbs up, John.  Your code looks great!
